/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.LivroVO;
import modelo.PrateleiraVO;
import modelo.helper.PrateleiraHelper;

/**
 *
 * @author geraldo
 */
public class PrateleiraGUI extends javax.swing.JDialog {

    /** Helper para Pralereira */
    private PrateleiraHelper prateleiraHelper;
    
    /**
     * Creates new form PrateleiraGUI
     */
    public PrateleiraGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prateleiraHelper = PrateleiraHelper.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCodigo.setText("Código");

        lblDescricao.setText("Descrição");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblDescricao))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(txtCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnPesquisar)
                    .addComponent(btnIncluir))
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnExcluir, btnIncluir, btnPesquisar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluir))
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        try{
            int codigo = Integer.parseInt(txtCodigo.getText());
            PrateleiraVO prateleiraVO= prateleiraHelper.pesquisarPrateleira(codigo);
            
            if (prateleiraVO!=null)
            {
                txtDescricao.setText(prateleiraVO.getDescricao());
            }
            else{
                JOptionPane.showMessageDialog(this, "Registro não encontrado!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Valor de código inálido!");
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
        int codigo=0;
        String descricao=null;
        int quantidade=-1;
        
        try{
            if (txtCodigo.getText()==null || txtCodigo.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Código obrigatório!");
            }
            else{
                codigo=Integer.parseInt(txtCodigo.getText());
                descricao=txtDescricao.getText();
                
                PrateleiraVO temp=new PrateleiraVO(codigo, descricao);
                
                quantidade=prateleiraHelper.adicionarPrateleira(temp);
                
                if (quantidade>0){
                    JOptionPane.showMessageDialog(this, "Prateleira incluída com sucesso!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Registro não foi incluído!");
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valor de código inálido!");
        }         
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        int codigo=0;
        String descricao=null;
        int quantidade=-1;
        PrateleiraVO prateleiraVO=null;
        
        try{
            if (txtCodigo.getText()==null || txtCodigo.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Código obrigatório!");
            }
            else{
                codigo=Integer.parseInt(txtCodigo.getText());
                descricao=txtDescricao.getText();
                
                prateleiraVO=prateleiraHelper.pesquisarPrateleira(codigo);
                
                if (prateleiraVO!=null){
                    prateleiraVO.setDescricao(descricao);
                    JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Registro não foi encontrado!");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Valor de código inálido!");
        }        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int quantidade=0, codigo=0;
        PrateleiraVO livro=null;
        
        try{
            if (txtCodigo.getText()==null || txtCodigo.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Código obrigatório!");
            }
            else{
                codigo=Integer.parseInt(txtCodigo.getText());
                quantidade=prateleiraHelper.removerPrateleira(new PrateleiraVO(codigo));
                if (quantidade>0){
                    JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!");
                    txtCodigo.setText("");
                    txtDescricao.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Registro não encontrado!");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Valor de código inálido!");
        }        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrateleiraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrateleiraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrateleiraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrateleiraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrateleiraGUI dialog = new PrateleiraGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
